export const ALL_BREEDS = [
    { key: "Abyssinian", value: "Abyssinian" },
    { key: "American Bobtail", value: "American Bobtail" },
    { key: "American Curl", value: "American Curl" },
    { key: "American Shorthair", value: "American Shorthair" },
    { key: "American Wirehair", value: "American Wirehair" },
    { key: "Australian Mist", value: "Australian Mist" },
    { key: "Balinese", value: "Balinese" },
    { key: "Bengal", value: "Bengal" },
    { key: "Birman", value: "Birman" },
    { key: "Bombay", value: "Bombay" },
    { key: "British Shorthair", value: "British Shorthair" },
    { key: "Burmese", value: "Burmese" },
    { key: "Burmilla", value: "Burmilla" },
    { key: "Chartreux", value: "Chartreux" },
    { key: "Chausie", value: "Chausie" },
    { key: "Cornish Rex", value: "Cornish Rex" },
    { key: "Cymric", value: "Cymric" },
    { key: "Devon Rex", value: "Devon Rex" },
    { key: "Donskoy", value: "Donskoy" },
    { key: "Egyptian Mau", value: "Egyptian Mau" },
    { key: "Exotic Shorthair", value: "Exotic Shorthair" },
    { key: "Havana", value: "Havana" },
    { key: "Himalayan", value: "Himalayan" },
    { key: "Japanese Bobtail", value: "Japanese Bobtail" },
    { key: "Khaomanee", value: "Khaomanee" },
    { key: "Korat", value: "Korat" },
    { key: "Kurilian Bobtail", value: "Kurilian Bobtail" },
    { key: "LaPerm", value: "LaPerm" },
    { key: "Lykoi", value: "Lykoi" },
    { key: "Maine Coon", value: "Maine Coon" },
    { key: "Manx", value: "Manx" },
    { key: "Minuet", value: "Minuet" },
    { key: "Munchkin", value: "Munchkin" },
    { key: "Nebelung", value: "Nebelung" },
    { key: "Norwegian Forest", value: "Norwegian Forest" },
    { key: "Ocicat", value: "Ocicat" },
    { key: "Oriental", value: "Oriental" },
    { key: "Persian", value: "Persian" },
    { key: "Peterbald", value: "Peterbald" },
    { key: "Pixiebob", value: "Pixiebob" },
    { key: "Ragdoll", value: "Ragdoll" },
    { key: "Russian Blue", value: "Russian Blue" },
    { key: "Savannah", value: "Savannah" },
    { key: "Scottish Fold", value: "Scottish Fold" },
    { key: "Scottish Straight", value: "Scottish Straight" },
    { key: "Selkirk Rex", value: "Selkirk Rex" },
    { key: "Siamese", value: "Siamese" },
    { key: "Siberian", value: "Siberian" },
    { key: "Singapura", value: "Singapura" },
    { key: "Snowshoe", value: "Snowshoe" },
    { key: "Somali", value: "Somali" },
    { key: "Sphynx", value: "Sphynx" },
    { key: "Thai", value: "Thai" },
    { key: "Tonkinese", value: "Tonkinese" },
    { key: "Toyger", value: "Toyger" },
    { key: "Turkish Angora", value: "Turkish Angora" },
    { key: "Turkish Van", value: "Turkish Van" },
    { key: "Others", value: "Others" },
];